services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    depends_on:
      - db
    environment:
      JWT_SECRET: ${JWT_SECRET:-dev-change-me}
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      PERSIST: ${PERSIST:-memory}

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
